"""
User Models
===========

Data models for user-related entities.

Includes:
- User: Core user account information
- UserProfile: Extended user preferences and progress
- StudySession: Record of learning activity

These models map to the database tables defined in schema.py
and are used by the repository layer for data transfer.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from .base import BaseModel


@dataclass(frozen=True)
class User(BaseModel):
    """
    Core user account model.
    
    Represents a user account with basic identification.
    Maps to the 'users' table in the database.
    
    Attributes:
        id: Unique identifier (auto-generated by DB)
        name: Display name of the user (required)
        email: Unique email address (required, used for login)
        created_at: Account creation timestamp (auto-generated)
    
    Example:
        >>> user = User(name="Marie", email="marie@example.com")
        >>> print(user)
        User(id=None, name='Marie', email='marie@example.com', created_at=None)
    """
    id: Optional[int] = None
    name: str = ""
    email: str = ""
    created_at: Optional[datetime] = None
    
    @classmethod
    def from_row(cls, row) -> "User":
        """
        Create a User from a database row.
        
        Args:
            row: sqlite3.Row with columns: id, name, email, created_at
            
        Returns:
            User instance populated from the row
            
        Example:
            cursor.execute("SELECT * FROM users WHERE id = ?", (1,))
            row = cursor.fetchone()
            user = User.from_row(row)
        """
        return cls(
            id=row["id"],
            name=row["name"],
            email=row["email"],
            created_at=row["created_at"] if row["created_at"] else None
        )


@dataclass(frozen=True)
class UserProfile(BaseModel):
    """
    Extended user profile with learning preferences.
    
    Contains language learning specific information.
    Maps to the 'user_profiles' table.
    
    Attributes:
        id: Unique identifier (auto-generated)
        user_id: Foreign key to users.id (required)
        cefr_level: French proficiency level (A1-C2)
        native_language: User's native language code (e.g., 'en', 'es')
        learning_goal: User's stated learning objective
        daily_streak: Consecutive days of study
        total_xp: Accumulated experience points
        updated_at: Last profile update timestamp
    
    Example:
        >>> profile = UserProfile(
        ...     user_id=1,
        ...     cefr_level="A2",
        ...     learning_goal="Travel to France"
        ... )
    """
    id: Optional[int] = None
    user_id: int = 0
    cefr_level: Optional[str] = None  # A1, A2, B1, B2, C1, C2
    native_language: str = "en"
    learning_goal: Optional[str] = None
    daily_streak: int = 0
    total_xp: int = 0
    updated_at: Optional[datetime] = None
    
    # Valid CEFR levels
    VALID_CEFR_LEVELS = {"A1", "A2", "B1", "B2", "C1", "C2"}
    
    def is_valid_cefr(self) -> bool:
        """Check if the CEFR level is valid."""
        return self.cefr_level is None or self.cefr_level in self.VALID_CEFR_LEVELS
    
    @classmethod
    def from_row(cls, row) -> "UserProfile":
        """Create a UserProfile from a database row."""
        return cls(
            id=row["id"],
            user_id=row["user_id"],
            cefr_level=row["cefr_level"],
            native_language=row["native_language"],
            learning_goal=row["learning_goal"],
            daily_streak=row["daily_streak"],
            total_xp=row["total_xp"],
            updated_at=row["updated_at"] if row["updated_at"] else None
        )


@dataclass(frozen=True)
class StudySession(BaseModel):
    """
    Record of a user's learning session.
    
    Tracks when users study, what they did, and how much XP they earned.
    Maps to the 'study_sessions' table.
    
    Attributes:
        id: Unique identifier (auto-generated)
        user_id: Foreign key to users.id (required)
        session_date: When the session occurred
        duration_minutes: Length of the study session
        activity_type: Type of learning activity
        xp_earned: Experience points gained
    
    Example:
        >>> session = StudySession(
        ...     user_id=1,
        ...     duration_minutes=30,
        ...     activity_type="vocabulary",
        ...     xp_earned=60
        ... )
    """
    id: Optional[int] = None
    user_id: int = 0
    session_date: Optional[datetime] = None
    duration_minutes: int = 0
    activity_type: str = ""  # vocabulary, grammar, listening, speaking, etc.
    xp_earned: int = 0
    
    # Valid activity types
    VALID_ACTIVITIES = {
        "vocabulary", "grammar", "listening", "speaking", 
        "reading", "writing", "conversation", "quiz", "review"
    }
    
    def is_valid_activity(self) -> bool:
        """Check if the activity type is valid."""
        return self.activity_type in self.VALID_ACTIVITIES
    
    @classmethod
    def from_row(cls, row) -> "StudySession":
        """Create a StudySession from a database row."""
        return cls(
            id=row["id"],
            user_id=row["user_id"],
            session_date=row["session_date"] if row["session_date"] else None,
            duration_minutes=row["duration_minutes"],
            activity_type=row["activity_type"],
            xp_earned=row["xp_earned"]
        )
